### ISSUE TITLE
Cannot download the latest builds :( Also, a question?

### ISSUE THREAD

**Issue by informer2016** [xenos1984/NOS#1]
@xenos1984 , good day, currently I am updating the OSDev wiki ( Projects page ).
Wanted to check if your OS fits on a floppy _(the floppies still could be used today,
e.g. as the virtual floppies inside the open source coreboot BIOS)_
But sadly cannot download the latest build, it tells me "Error 500"

Please could you fix it? And also tell - how much your ISO weights,
and is there any theoretical possibility of your OS release as a live floppy?

**Comment by xenos1984** [comment]
The issue with downloading the latest build was related to an API change at CircleCI. As a temporary workaround, I created a redirect to the correct file and changed the links in https://github.com/xenos1984/NOS/commit/73899a9a44bc2e25ced69d07adaef9d2d2883378. Please check whether the build can be downloaded now.

Regarding your question, the size of an ISO should be around 100 kB, and so the kernel would also fit on a floppy. However, creating a floppy from scratch requires a few more tools, so creating a live ISO instead is much easier on CircleCI. But if you have any suggestions how to automatically create a floppy image from scratch, I can try to implement them.

**Comment by xenos1984** [comment]
I have created a release, which is updated automatically when an automatic build (triggered after a git push) succeeds, and which contains two bootable ISO files (i686 and x86_64), each of them with four differently compiled versions of the kernel:

https://github.com/xenos1984/NOS/releases/tag/latest

I'll mark this issue as an enhancement (still need to create a floppy image at some point) and leave it open.

**Comment by informer2016** [comment]
@xenos1984 Happy New Year ! It is possible to borrow the floppy creation method from another hobby OS like this one _(small code)_ - https://github.com/NANO-DEV/NANO-S16 - but I am unsure if that could be imported to CircleCI, not familiar with this build system

**Comment by xenos1984** [comment]
Happy New Year!

I had a look at the linked OS, and that one uses a custom boot loader. I'm using GRUB2, so I would rather need an automated way to install it to a floppy image (without manually tinkering with sector offsets) - probably using grub-install. My kernel also boots from GRUB Legacy, which I originally used on a floppy image, but updating it required more work manual work, and GRUB Legacy is no longer maintained. Hence the switch to GRUB2 + CD image instead.

If your only goal is to boot an image on bare metal, then this can also be achieved with the provided ISO images, provided you have GRUB2 installed on the machine you boot. (I used this to boot straignt into a Linux DVD image, for example, so I could run the installation completely from an image.)

http://www.gnu.org/software/grub/manual/grub/html_node/loopback.html

**Comment by xenos1984** [comment]
The automatic latest release of NOS now includes FAT12 and EXT2 formatted GRUB2 floppy images.

https://github.com/xenos1984/NOS/releases/tag/latest
