### ISSUE TITLE
Boot modules: not found, PageFault occurred

### ISSUE THREAD

**Issue by informer2016** [xenos1984/NOS#2]
@xenos1984 Thank you very much for creating a floppy build ! :heart: 

_"Boot modules: not found, PageFault occurred"_ seems to be the universal problem:
regardless of what media _(Floppy/ISO)_, FS _(EXT2/FAT12)_, architecture _(x86_64/i686)_
and what boot option I choose _(with/without SMP/ACPI)_ - there's always this message below :

Maybe it could be a software/hardware incompatibility with my setup
_(trying to run NOS in a VirtualBox 5.2.4 under Ubuntu 16.04, all on AMD CPU)_

![nos_boot_modules](https://user-images.githubusercontent.com/26509528/34798093-bf67f3f8-f66b-11e7-95af-778750ae1b0e.png)

**Comment by xenos1984** [comment]
This fault is simply due to a restructuring of the code, which is not fully complete yet - some parts have not been re-enabled yet, causing this fault. Also there simply are no boot modules yet, because the module loader is in the process of being restructured. This will be fixed once the restructuring is done.

**Comment by informer2016** [comment]
Good day @xenos1984 ! By the way QEMU has the same problem... Are there any more modern floppy builds?

**Comment by xenos1984** [comment]
The floppy builds are up to date with the current code. This is work in progress. There simply are no boot modules at the current development stage.

**Comment by informer2016** [comment]
@xenos1984 I see. Will be checking your NOS project once in a while, and after it goes to the next level I'll be able to test NOS as a part of my coreboot+SeaBIOS build :wink: Wish you a nice coming holidays

**Comment by xenos1984** [comment]
The page fault has been resolved during further code restructuring.
