### ISSUE TITLE
could you please add instruction how to boot up?

### ISSUE THREAD

**Issue by gwnet** [xenos1984/NOS#3]
this can boot up from qemu or VMware work station? can you write down detail steps?

**Comment by xenos1984** [comment]
Compiling for a PC target yields a .iso CD image (which can also be downloaded from GitHub releases). This can be booted in any virtual machine, such as qemu or VMware. See the documentation of your virtual machine on how to boot a CD image.

**Comment by gwnet** [comment]
I use vmware workstation 15 to boot your OS. it show me below error.
![image](https://user-images.githubusercontent.com/7543276/76943818-ee954100-693a-11ea-8d99-4add8cb814ed.png)
![image](https://user-images.githubusercontent.com/7543276/76943915-15537780-693b-11ea-816f-07d04bbd99b9.png)

**Comment by gwnet** [comment]
![image](https://user-images.githubusercontent.com/7543276/76943975-31571900-693b-11ea-9dcb-f677a514d24c.png)

**Comment by gwnet** [comment]
![1](https://user-images.githubusercontent.com/7543276/76944083-5ea3c700-693b-11ea-8098-9406c580a03d.jpg)

**Comment by xenos1984** [comment]
It seems that your VMware version does not support xsetbv:

http://www.felixcloutier.com/x86/xsetbv

**Comment by AkibAzmain** [comment]
**Warning**: This project has no license and all rights are reserved. So, don't even download it (let alone compile and run), or you'll violate copyright law.
