### ISSUE TITLE
fail to compile on ubuntu 18.04

### ISSUE THREAD

**Issue by gwnet** [xenos1984/NOS#4]
hello I suffer this error. I can build all other things like SPDK, pmem project well on this machine. Could you please check this error? 
wayne@ubuntu:~/NOS$ sudo ./configure x86_64-pc-elf
configure: WARNING: you should use --build, --host, --target
checking build system type... x86_64-pc-elf
checking host system type... x86_64-pc-elf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for x86_64-pc-elf-g++... no
checking for x86_64-pc-elf-c++... no
checking for x86_64-pc-elf-gpp... no
checking for x86_64-pc-elf-aCC... no
checking for x86_64-pc-elf-CC... no
checking for x86_64-pc-elf-cxx... no
checking for x86_64-pc-elf-cc++... no
checking for x86_64-pc-elf-cl.exe... no
checking for x86_64-pc-elf-FCC... no
checking for x86_64-pc-elf-KCC... no
checking for x86_64-pc-elf-RCC... no
checking for x86_64-pc-elf-xlC_r... no
checking for x86_64-pc-elf-xlC... no
checking for g++... g++
checking whether the C++ compiler works... no
configure: error: in `/home/wayne/NOS':
configure: error: C++ compiler cannot create executables
See `config.log' for more details

**Comment by gwnet** [comment]
e=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1~18.10.1)
configure:3201: $? = 0
configure:3190: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:3201: $? = 1
configure:3190: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'; did you mean '--version'?
g++: fatal error: no input files
compilation terminated.
configure:3201: $? = 1
configure:3221: checking whether the C++ compiler works
configure:3243: g++  -mcmodel=kernel -mno-red-zone -mgeneral-regs-only -O2 -ffreestanding -fno-leading-underscore -Wall -Wextra -Wpedantic -fno-rtti -fno-exceptions -std=c++17   -Wl,-z -Wl,max-page-size=0x1000 -nostartfiles -nostdlib -fno-rtti -fno-exceptions conftest.cpp  >&5
cc1plus: error: code model kernel does not support PIC mode
configure:3247: $? = 1
configure:3285: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "NOS"
| #define PACKAGE_TARNAME "nos"
| #define PACKAGE_VERSION "0.1"
| #define PACKAGE_STRING "NOS 0.1"

**Comment by xenos1984** [comment]
The correct format to specify a target triplet is to use `--host=<target-triplet>`. This has been clarified in the compile instructions in the readme file.

**Comment by gwnet** [comment]
thank you so much. my bad. after I use --host=, I still suffer the same error.

wayne@ubuntu:~/NOS$ sudo ./configure --host=x86_64-pc-elf
[sudo] password for wayne: 
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-elf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-pc-elf-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for x86_64-pc-elf-g++... no
checking for x86_64-pc-elf-c++... no
checking for x86_64-pc-elf-gpp... no
checking for x86_64-pc-elf-aCC... no
checking for x86_64-pc-elf-CC... no
checking for x86_64-pc-elf-cxx... no
checking for x86_64-pc-elf-cc++... no
checking for x86_64-pc-elf-cl.exe... no
checking for x86_64-pc-elf-FCC... no
checking for x86_64-pc-elf-KCC... no
checking for x86_64-pc-elf-RCC... no
checking for x86_64-pc-elf-xlC_r... no
checking for x86_64-pc-elf-xlC... no
checking for g++... g++
checking whether the C++ compiler works... no
configure: error: in `/home/wayne/NOS':
configure: error: C++ compiler cannot create executables
See `config.log' for more details

**Comment by xenos1984** [comment]
It appears that `configure` cannot find your cross compiler. Make sure that it is present in your system's `PATH`.
