### ISSUE TITLE
Can't find a license file

### ISSUE THREAD

**Issue by AkibAzmain** [xenos1984/NOS#5]
Can't find any ``COPYING`` or ``LICENSE`` file in the root directory of your source repo. What is the license of this OS? If you haven't licensed your OS, consider adding a copyleft license like GNU GPLv3.

**Comment by xenos1984** [comment]
There is no license for this project.

**Comment by AkibAzmain** [comment]
@xenos1984 If your OS has no license, it means that all rights are reserved and no one is allowed even to run the OS (except the copyright holder, you, of course).

**Comment by xenos1984** [comment]
This issue tracker is for technical issues, not legal questions.
